config/routes.rb
Rails.application.routes.draw do
  get "page/index"

  resources :documentary_films
  #resources :series
  resources :series
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "page#index"
end

app/models/film.rb
# == Schema Information
#
# Table name: films
#
#  id         :bigint           not null, primary key
#  name       :string
#  sinopsis   :string
#  director   :string
#  imagen     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  categoria  :integer
#
class Film < ApplicationRecord


end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :set_film, only: %i[ show edit update destroy ]



  # GET /films or /films.json
  def index
    @films = Film.all
  end

  # GET /films/1 or /films/1.json
  def show
    
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
     #agregado para validar la ruta URL
     @film = Film.find(params[:id]) 
  end

  # POST /films or /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: "La pelicula fue creada correctamente." }
        format.json { render :index, status: :created, location: @film }
      else
        # Si la base de datos no guarda el registro, se redirige a la vista de "new"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1 or /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: "La pelicula fue Actualizada." }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1 or /films/1.json
  def destroy
    @film.destroy!

    respond_to do |format|
      format.html { redirect_to films_path, status: :see_other, notice: "La pelicula fue borrada." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def film_params
      params.require(:film).permit(:name, :sinopsis, :director, :imagen)
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film.html.erb
<!-- controla los espacios vacios en card-tex -->
<div class="col">
  <%= javascript_include_tag "controllers/espaciovacio_controller" %>

  <div id="<%= dom_id film %>" class="row d-flex justify-content-center align-items-center gap-3 mt-5 " >
    <div class="card" style="width: 18rem;">
      <img src="<%= film.imagen %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= film.name %></h5>
        <p class="card-text {{ texto ? '' : 'empty-text' }}"><%= film.sinopsis %>.</p> <!-- controla que no exista texto vacio -->
        <% if params[:id] %>
          <% film = Film.find(params[:id]) %>
          <div id="<%= dom_id film %>">
            <p>
              <strong>Name:</strong>
              <%= film.name %>
            </p>
            <p>
              <strong>Director:</strong>
              <%= film.director %>
            </p>
            </div>
            <div class="d-flex justify-content-center gap-2">
              <%= link_to "Regresar", films_path, class: "btn btn-primary" %>
              <%= link_to "Editar", edit_film_path(@film), class: "btn btn-primary"%>
              <%= link_to "Eliminar", @film, method: :delete, class: "btn btn-danger" %>
            </div>
            <% else %>
            <%= link_to "Ver mas..", film, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/films/_form.html.erb
<%= form_with(model: film) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(film.errors.count, "error") %> encontrados, no se puede grabar:</h2>
      <ul>
        <% film.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>





<div class="row d-flex justify-content-center align-items-center">
  <div class="card mt-4" style="width: 18rem;">
    <% if !params[:new] %>
        <img src="<%= form.object.imagen%>" class="card-img-top" >
    <% end %>
    <div class="card-body">
        <h5 class="card-title"><%= form.object.name %></h5>
        <p class="card-text">
        <div>
          <%= form.label :Nombre, style: "display: block" %>
          <%= form.text_field :name, required: true %>
        </div>

        <div>
          <%= form.label :sinopsis, style: "display: block" %>
          <%= form.text_field :sinopsis, required: true %>
        </div>

        <div>
          <%= form.label :director, style: "display: block" %>
          <%= form.text_field :director, required: true %>
        </div>

        <div>
          <%= form.label :Caratula, style: "display: block" %>
          <%= form.text_area :imagen, id: "imagen_url", required: true %>
        </div>

      <div class="mt-2">
        <div class="mt-2">
          <% if @film.new_record? %>
            <%= form.submit "Grabar Pelicula", class: 'btn btn-primary' %>
          <% else %>    
            <%= form.submit "Actualizar Película", class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
      </p>
    </div>
  </div>
</div>


<% end %>

app/views/films/edit.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Pelicula', new_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button",  disabled: true   %>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>












  <% content_for :title, "Editing film" %>

  <div>
    <%= render "form", film: @film  %>
  </div>
  <div class="row d-flex justify-content-center align-items-center gap-3  ">
    <div class="col-6 mt-4 d-flex justify-content-center gap-3 mb-4">
      <%= link_to "Cancelar", @film , class: "btn btn-primary" %>
      <%= link_to "Peliculas", films_path, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>

app/views/films/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Pelicula', new_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button",  disabled: true   %>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>





 <div id="films">
 <h1 class="my-5">Nuestras Peliculas</h1>
  <div class="row row-cols-1 row-cols-sm-4 row-cols-md-4 row-cols-lg-4 ">
      
    <% @films.each do |film| %>

      <%= render film %>

    <% end %>
  </div>
</div>

app/views/films/new.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Pelicula' , new_film_path, class:"nav-link disabled", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button",  disabled: true   %>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>





<% content_for :title, "New film" %>

<h1>Crear Pelicula</h1>

<div class="row center-content ">
  <%= render "form", film: @film %>
</div>
<div class="d-flex justify-content-center gap-2 py-5">

  <%= link_to "Regresar a Peliculas", films_path , class: "btn btn-primary" %>
</div>

app/views/films/show.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Pelicula', new_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button",  disabled: true   %>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button" %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>





<%= render @film %>