config/routes.rb
Rails.application.routes.draw do
  get "page/index"

  resources :documentary_films
  #resources :series
  resources :series
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "page#index"
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
   @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: "La serie fue creada correctamente" }
        format.json { render :index, status: :created, location: @series }
      else
        # Si la base de datos no guarda el registro, se redirige a la vista de "new"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: "Serie fue actualizada." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy!

    respond_to do |format|
      format.html { redirect_to series_index_path, status: :see_other, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:name, :sinopsis, :director, :imagen)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> encontrados, no se puede grabar:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>






<div class="row d-flex justify-content-center align-items-center">
  <div class="card mt-4" style="width: 18rem;">
    <% if !params[:new] %>
    <img src="<%= form.object.imagen%>" class="card-img-top" >
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= form.object.name %></h5>
      <p class="card-text">
      <div>
      <%= form.label :Nombre, style: "display: block" %>
      <%= form.text_field :name, required: true %>
    </div>

    <div>
      <%= form.label :sinopsis, style: "display: block" %>
      <%= form.text_field :sinopsis, required: true %>
    </div>

    <div>
      <%= form.label :director, style: "display: block" %>
      <%= form.text_field :director, required: true %>
    </div>

    <div>
      <%= form.label :Caratula, style: "display: block" %>
      <%= form.text_area :imagen, id: "imagen_url", required: true %>
    </div>

    <div class="mt-2">

      <%
=begin%>
 <% if params[:new] %>
        <%= form.submit "Grabar Pelicula", class: 'btn btn-primary' %>
      <% else %>    
        <%= form.submit "Actualizar Película", class: 'btn btn-primary' %>
      <% end %> 
<%
=end%>
      
      <div class="mt-2">
  <% if @series.new_record? %>
    <%= form.submit "Grabar Serie", class: 'btn btn-primary' %>
  <% else %>    
    <%= form.submit "Actualizar Serie", class: 'btn btn-primary' %>
  <% end %>
</div>




    </div>
    </p>
      
    </div>
  </div>
</div>


<% end %>





















<%
=begin%>
 

<%= form_with(model: series) do |form| %>
  <% if series.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
        <% series.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :sinopsis, style: "display: block" %>
    <%= form.text_field :sinopsis %>
  </div>

  <div>
    <%= form.label :director, style: "display: block" %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :imagen, style: "display: block" %>
    <%= form.text_area :imagen %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %> 
<%
=end%>

app/views/series/_series.html.erb
<div class="col">
  <%= javascript_include_tag "controllers/espaciovacio_controller" %>

  <div id="<%= dom_id series %>" class="row d-flex justify-content-center align-items-center gap-3 mt-5 " >
        <div class="card" style="width: 18rem;">
          <img src="<%= series.imagen %>" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title"><%= series.name %></h5>
              <p class="card-text {{ texto ? '' : 'empty-text' }}"><%= series.sinopsis %>.</p> <!-- controla que no exista texto vacio -->

              <% if params[:id] %>
                <% film = Series.find(params[:id]) %>
                <div id="<%= dom_id series %>">
                  <p>
                    <strong>Name:</strong>
                    <%= series.name %>
                  </p>
                  <p>
                    <strong>Director:</strong>
                    <%= series.director %>
                  </p>
                </div>
                <div class="d-flex justify-content-center gap-2">
                    <%= link_to "Regresar", series_index_path, class: "btn btn-primary" %>
                    <%= link_to "Editar", edit_series_path(@series), class: "btn btn-primary"%>
                    <%= link_to "Eliminar", @series, method: :delete, class: "btn btn-danger" %>
                  </div>

              <% else %>
                <%= link_to "Ver mas..", series, class: "btn btn-primary" %>
              <% end %>
              
            </div>
        </div>

  </div>
</div>  















<%
=begin%>
 

<div id="<%= dom_id series %>">
  <p>
    <strong>Name:</strong>
    <%= series.name %>
  </p>

  <p>
    <strong>Sinopsis:</strong>
    <%= series.sinopsis %>
  </p>

  <p>
    <strong>Director:</strong>
    <%= series.director %>
  </p>

  <p>
    <strong>Imagen:</strong>
    <%= series.imagen %>
  </p>

</div> 
<%
=end%>

app/views/series/edit.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Serie', new_series_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button",  disabled: true    %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>






  <% content_for :title, "Editing Serie" %>

  <div>
    <%= render "form", series: @series  %>
  </div>
  <div class="row d-flex justify-content-center align-items-center gap-3  ">
    <div class="col-6 mt-4 d-flex justify-content-center gap-3 mb-4">
      <%= link_to "Cancelar", @series, class: "btn btn-primary" %>
      <%= link_to "Series", series_index_path, method: :delete, class: "btn btn-danger" %>
    </div>
  </div>






<%
=begin%>
 


<% content_for :title, "Editing series" %>

<h1>Editing series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Show this series", @series %> |
  <%= link_to "Back to series", series_index_path %>
</div> 
<%
=end%>

app/views/series/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Serie', new_series_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button",  disabled: true    %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>






 <div id="series">
  <h1 class="my-5">Nuestras Series</h1>
  <div class="row row-cols-1 row-cols-sm-4 row-cols-md-4 row-cols-lg-4 ">
      
    <% @series.each do |series| %>

      <%= render series %>

    <% end %>
  </div>
</div>







<%
=begin%>
 
<p style="color: green"><%= notice %></p>

<% content_for :title, "Series" %>

<h1>Series</h1>

<div id="series">
  <% @series.each do |series| %>
    <%= render series %>
    <p> 
<%
=end%>
      <%
=begin%>
 <%= link_to "Show this series", series %> 
<%

    </p>
  <% end %>
</div>
=end%>
<%
=begin%>
 <%= link_to "New series", new_series_path %> 
<%
=end%>

app/views/series/new.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Serie' , new_film_path, class:"nav-link disabled", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button",  disabled: true    %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>





<% content_for :title, "Nueva Serie" %>

<h1>Crear Serie</h1>

<div class="row center-content ">
  <%= render "form", series: @series %>
</div>
<div class="d-flex justify-content-center gap-2 py-5">

  <%= link_to "Regresar a Series", series_index_path , class: "btn btn-primary" %>
</div>



<%
=begin%>
 
<% content_for :title, "New series" %>

<h1>New series</h1>

<%= render "form", series: @series %>

<br>

<div>
  <%= link_to "Back to series", series_index_path %>
</div> 
<%
=end%>

app/views/series/show.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Serie', new_series_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button " %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button",  disabled: true    %>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>













<%
=begin%>
 

<p style="color: green"><%= notice %></p> 
<%
=end%>

<%= render @series %>

<%
=begin%>
 <div>
  <%= link_to "Edit this series", edit_series_path(@series) %> |
  <%= link_to "Back to series", series_index_path %>

  <%= button_to "Destroy this series", @series, method: :delete %>
</div> 
<%
=end%>