config/routes.rb
Rails.application.routes.draw do
  get "page/index"

  resources :documentary_films
  #resources :series
  resources :series
  resources :films
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "page#index"
end

app/models/documentary_film.rb
# == Schema Information
#
# Table name: documentary_films
#
#  id         :bigint           not null, primary key
#  name       :string
#  sinopsis   :string
#  director   :string
#  imagen     :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  categoria  :integer
#
class DocumentaryFilm < ApplicationRecord
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  before_action :set_documentary_film, only: %i[ show edit update destroy ]

  # GET /documentary_films or /documentary_films.json
  def index
    @documentary_films = DocumentaryFilm.all
  end

  # GET /documentary_films/1 or /documentary_films/1.json
  def show
  end

  # GET /documentary_films/new
  def new
    @documentary_film = DocumentaryFilm.new
  end

  # GET /documentary_films/1/edit
  def edit
    #validar de donde viene
    
    #@documentary_film=Documentary_film.find(params[:id])
    
  end

  # POST /documentary_films or /documentary_films.json
  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)

    respond_to do |format|
      if @documentary_film.save
        format.html { redirect_to @documentary_film, notice: "El documental fue creado correctamente" }
        format.json { render :index, status: :created, location: @documentary_film }
      else
        # Si la base de datos no guarda el registro, se redirige a la vista de "new"
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @documentary_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documentary_films/1 or /documentary_films/1.json
  def update
    respond_to do |format|
      if @documentary_film.update(documentary_film_params)
        format.html { redirect_to @documentary_film, notice: "Documental fue actualizado." }
        format.json { render :show, status: :ok, location: @documentary_film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @documentary_film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documentary_films/1 or /documentary_films/1.json
  def destroy
    @documentary_film.destroy!

    respond_to do |format|
      format.html { redirect_to documentary_films_path, status: :see_other, notice: "Documentary film was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_documentary_film
      @documentary_film = DocumentaryFilm.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def documentary_film_params
      params.require(:documentary_film).permit(:name, :sinopsis, :director, :imagen)
    end
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/views/documentary_films/_documentary_film.html.erb
<!-- controla los espacios vacios en card-tex -->
<div class="col">
  <%= javascript_include_tag "controllers/espaciovacio_controller" %>

  <div id="<%= dom_id documentary_film %>" class="row d-flex justify-content-center align-items-center gap-3 mt-5 " >
    <div class="card" style="width: 18rem;">
      <img src="<%= documentary_film.imagen %>" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= documentary_film.name %></h5>
        <p class="card-text {{ texto ? '' : 'empty-text' }}"><%= documentary_film.sinopsis %></p> <!-- controla que no exista texto vacio -->
        <% if params[:id] %>
          <% documentary_film = DocumentaryFilm.find(params[:id]) %>
          <div id="<%= dom_id documentary_film %>">
            <p>
              <strong>Name:</strong>
              <%= documentary_film.name %>
            </p>
            <p>
              <strong>Director:</strong>
              <%= documentary_film.director %>
            </p>
          </div>
          <div class="d-flex justify-content-center gap-2">
            <%= link_to "Regresar", documentary_films_path, class: "btn btn-primary" %>
            <%= link_to "Editar", edit_documentary_film_path(@documentary_film), class: "btn btn-primary"%>
            <%= link_to "Eliminar", @documentary_film, method: :delete, class: "btn btn-danger" %>
          </div>
        <% else %>
            <%= link_to "Ver mas..", documentary_film, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>  

app/views/documentary_films/_form.html.erb
<%= form_with(model: documentary_film) do |form| %>
  <% if documentary_film.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(documentary_film.errors.count, "error") %> encontrados, no se puede grabar:</h2>
      <ul>
        <% documentary_film.errors.each do |error| %>
        <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




<div class="row d-flex justify-content-center align-items-center">
  <div class="card mt-4" style="width: 18rem;">
    <% if !params[:new] %>
      <img src="<%= form.object.imagen%>" class="card-img-top" >
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= form.object.name %></h5>
      <p class="card-text">
        <div>
          <%= form.label :Nombre, style: "display: block" %>
          <%= form.text_field :name, required: true %>
        </div>
        <div>
          <%= form.label :sinopsis, style: "display: block" %>
          <%= form.text_field :sinopsis, required: true %>
        </div>
        <div>
          <%= form.label :director, style: "display: block" %>
          <%= form.text_field :director, required: true %>
        </div>
        <div>
          <%= form.label :Caratula, style: "display: block" %>
          <%= form.text_area :imagen, id: "imagen_url", required: true %>
        </div>
        <div class="mt-2">
          <div class="mt-2">
            <% if @documentary_film.new_record? %>
              <%= form.submit "Grabar Documental", class: 'btn btn-primary' %>
            <% else %>    
              <%= form.submit "Actualizar Documental", class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </p>  
    </div>
  </div>
</div>
<% end %>

app/views/documentary_films/edit.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
          <%= link_to 'Crear Documental', new_documentary_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button", disabled: true %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>
<% content_for :title, "Editing documentary_film" %>
<div>
  <%= render "form", documentary_film: @documentary_film  %>
</div>
<div class="row d-flex justify-content-center align-items-center gap-3  ">
  <div class="col-6 mt-4 d-flex justify-content-center gap-3 mb-4">
    <%= link_to "Cancelar", @documentary_film , class: "btn btn-primary" %>
    <%= link_to "Documentales", documentary_films_path, method: :delete, class: "btn btn-danger" %>
  </div>
</div>

app/views/documentary_films/index.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Documental', new_documentary_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button", disabled: true %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button"%>
        </li>
      </ul>      
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>
<div id="documentary_films">
 <h1 class="my-5">Nuestras Documentales</h1>
  <div class="row row-cols-1 row-cols-sm-4 row-cols-md-4 row-cols-lg-4 ">
    <% @documentary_films.each do |documentary_film| %>
      <%= render documentary_film %>
    <% end %>
  </div>
</div>

<!-- <%= link_to "New film", new_film_path %> -->













<%
=begin%>
 



<p style="color: green"><%= notice %></p>

<% content_for :title, "Documentary films" %>

<h1>Documentary films</h1>

<div id="documentary_films">
  <% @documentary_films.each do |documentary_film| %>
    <%= render documentary_film %>
    <p>
      <%= link_to "Show this documentary film", documentary_film %>
    </p>
  <% end %>
</div>

<%= link_to "New documentary film", new_documentary_film_path %>


 
<%
=end%>

app/views/documentary_films/new.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Documental' , new_film_path, class:"nav-link disabled", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button", disabled: true %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<% content_for :title, "New film" %>
<h1>Crear Documental</h1>
<div class="row center-content ">
  <%= render "form", documentary_film: @documentary_film %>
</div>
<div class="d-flex justify-content-center gap-2 py-5">
  <%= link_to "Regresar a Documentales", documentary_films_path , class: "btn btn-primary" %>
</div>




<% content_for :title, "New documentary film" %>
<h1>New documentary film</h1>
<%= render "form", documentary_film: @documentary_film %>
<br>
<div>
  <%= link_to "Back to documentary films", documentary_films_path %>
</div> 
<%=end%>

app/views/documentary_films/show.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'AppEntreter', page_index_path, class:"navbar-brand", "arial-current" => "page"  %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Inicio', page_index_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
        <li class="nav-item">
            <%= link_to 'Crear Documental', new_documentary_film_path, class:"nav-link active", "arial-current" => "page"  %>
        </li>
      </ul>
      <ul class="list-unstyled mb-0 d-flex justify-content-center gap-2 mx-4">
        <li>
          <%= link_to 'Documentales', documentary_films_path, class: "btn btn-outline-primary btn-sm", role: "button", disabled: true %>
        </li>
        <li>
          <%= link_to 'Peliculas', films_path, class: "btn btn-outline-success btn-sm", role: "button"%>
        </li>
        <li>
          <%= link_to 'Series', series_index_path, class: "btn btn-outline-danger btn-sm", role: "button"%>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Buscar</button>
      </form>
    </div>
  </div>
</nav>
<%= render @documentary_film %>